team: aurora
email: muhammad.usman1@careem.com
slack: aurora-web-cicd
project: web
#source: github
#branch: master
#agent: ecsqa
#dockerenv: 848569320300.dkr.ecr.eu-west-1.amazonaws.com/cicd/tooling:mot_cicd_eb_k8s_202110061312

stages:
  - publish


jobs:
    - name: publish
      stage: publish
      cmd: make push-artifactory
      artifactsDir: __artifacts__
